app.py
from flask import Flask, redirect, render_template
from views import views

app = Flask(__name__, static_folder='static')

app.secret_key = 'MySecretKey'

app.register_blueprint(views, url_prefix = "/")

@app.route('/')
def home():
    return redirect('/about')

@app.route('/about')
def about():
    return render_template('about.html')

if __name__ == '__main__':
    app.run(debug = True, port = 5000)

views.py
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
from database import data_fetch, update_pass, data_fill
import hashlib
from datetime import datetime


views = Blueprint('views', __name__)

@views.route('/login', methods=['GET', 'POST'])
def login():
    no_records = False

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user_data = data_fetch(email, str(hashlib.sha1(password.encode()).hexdigest()))
        if user_data:
            user_data = user_data[0]
            session['user_data'] = user_data
            print(f"Logged in user: {session['user_data']['primaryKey']}")
            return redirect(url_for('views.profile'))
        else:
            no_records = True

    return render_template('login.html', no_records=no_records)



@views.route('/reg', methods=['GET', 'POST'])
def reg():
    if request.method == 'POST':
        user_data = {
            'primaryKey': hashlib.sha1((request.form['email']+str(hashlib.sha1(request.form['password'].encode()).hexdigest())).encode()).hexdigest(),
            'name': request.form['name'],
            'age': request.form['age'],
            'gender': request.form['gender'],
            'linkedinProfURL': request.form['linkedinProfURL'],
            'designation': request.form['designation'],
            'country': request.form['country'],
            'disabled': request.form['disabled'],
            'FreshExp': request.form['FreshExp'],
            'joinedDate': datetime.now().strftime("%B %d, %Y"),
            'profileDescription': request.form['profileDescription'],
            'username': request.form['username'],
            'email': request.form['email'],
            'password': request.form['password'],
        }

        data_fill(**user_data)
        print('New User Registered!')

        # Use the user_data dictionary as needed (e.g., store it in a database)


        return render_template('login.html', user_data=user_data)
    return render_template('reg.html')


# views.py
@views.route('/profile')
def profile():
    if 'user_data' in session:  # Updated key to 'user_data'
        # Retrieve user_data from the session
        user_data = session.get('user_data', None)
        print('profile', user_data)
        print(user_data)
        if user_data is not None:
            # Render the profile template with user data
            return render_template('profile.html', user=user_data)
        else:
            # Handle the case where user_data is not provided
            return render_template('profile.html', user={})
    else:
        return redirect(url_for('views.login'))





@views.route('/passreset', methods=['GET', 'POST'])
def passreset():
    if request.method == 'POST':
        email = request.form.get('email')
        new_password = request.form.get('new_password')
        confirm_password = request.form.get('confirm_password')

        if new_password == confirm_password:
            flash('Password successfully reset. Please login with your new password.', 'success')
            update_pass(email, new_password)
            return redirect(url_for('views.login'))
        else:
            flash('Passwords do not match. Please try again.', 'error')

    return render_template('passreset.html')


@views.route('/logout', methods=['POST'])
def logout():
    if 'user' in session:
        username = session['user']
        session.pop('user', None)
        print(f'Logout successful for {username}', 'success')
    return redirect(url_for('views.login'))

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='about.css') }}">
    <title>About Page</title>
</head>
<body>

    <h1>About Page</h1>
    <p><b>Data Source:</b> In this project, we generated 200 records randomly using various packages in Python.</p>
    <p><b>Definition of Each Variable:</b> Below Table shows the definition of each variable.</p>
    
    <div class="table-container">
        <table>
            <tr>
                <th>Data</th>
                <th>Values</th>
            </tr>
            <tr>
                <td>primaryKey</td>
                <td>Unique identifier for each record.</td>
            </tr>
            <tr>
                <td>name</td>
                <td>Full name of the individual.</td>
            </tr>
            <tr>
                <td>age</td>
                <td>Age of the individual.</td>
            </tr>
            <tr>
                <td>gender</td>
                <td>Gender of the individual.</td>
            </tr>
            <tr>
                <td>linkedinProfURL</td>
                <td>LinkedIn profile URL of the individual.</td>
            </tr>
            <tr>
                <td>designation</td>
                <td>Job title or designation of the individual.</td>
            </tr>
            <tr>
                <td>country</td>
                <td>Country of residence of the individual.</td>
            </tr>
            <tr>
                <td>disabled</td>
                <td>Boolean indicating whether the individual has a disability.</td>
            </tr>
            <tr>
                <td>FreshExp</td>
                <td>Freshness of experience in the field.</td>
            </tr>
            <tr>
                <td>joinedDate</td>
                <td>Date when the individual joined the organization.</td>
            </tr>
            <tr>
                <td>profileDescription</td>
                <td>Brief description of the individual's professional profile.</td>
            </tr>
            <tr>
                <td>username</td>
                <td>Username used by the individual.</td>
            </tr>
            <tr>
                <td>email</td>
                <td>Email address of the individual.</td>
            </tr>
            <tr>
                <td>password</td>
                <td>Password associated with the individual's account.</td>
            </tr>
        </table>
    </div>
    <div>
        <p><b>1. <a href="{{ url_for('views.login') }}">Login:</a></b> We can Login with the right credentials on this page.</p>
        <p><b>2. <a href="{{ url_for('views.reg') }}">Registration:</a></b> We can register after filling our details on this page.</p>
        <p><b>3. <a href="{{ url_for('views.profile') }}">Profile:</a></b> After login with the right credentials, we can view our details on this page.</p>
        <p><b>4. <a href="{{ url_for('views.passreset') }}">Password Reset:</a></b> We reset our password if forgot on this page.</p>
        <p><b>NOTE:</b> In order to check the project/website properly, Please start with Login Page and not any other. From Login
            Page you can access other pages accordingly.<br>DO NOT OPEN/ACCESS THE PROJECT AS A SUB FOLDER. IN ORDER TO MAKE IT 
            WORK PROPERLY, PLEASE OPEN THE PROJECT AS A MAIN FOLDER.</p>
    </div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>

<body>
  <div class="container">
    <div class="wrapper">
      <div class="title"><span>Login</span></div>
      <form method="POST" action="{{ url_for('views.login') }}">
        <div class="row">
          <div class="row">
            <div class="icon"><i class="fas fa-user"></i></div>
            <input type="text" name="email" placeholder="Email or Phone" required>
          </div>
          <div class="row">
            <div class="icon"><i class="fas fa-lock"></i></div>
            <input type="password" name="password" id="passwordField" placeholder="Password" required>
            <div class="show-password-icon">
              <i class="fas fa-eye" id="togglePassword"></i>
            </div>
          </div>
          
        <div class="pass"><a href="{{ url_for('views.passreset') }}">Forgot password?</a></div>
        <div class="row button">
          <input type="submit" value="Login">
        </div>
        <div class="reg-link">Not a member? <a href="{{ url_for('views.reg') }}">Signup now</a></div>
      </form>
        <script>
          alert('No records found. Please check your email and password.');
          const togglePassword = document.getElementById('togglePassword');
          const passwordField = document.getElementById('passwordField');

          togglePassword.addEventListener('click', function () {
            const fieldType = passwordField.getAttribute('type');
            if (fieldType === 'password') {
              passwordField.setAttribute('type', 'text');
              togglePassword.classList.remove('fa-eye');
              togglePassword.classList.add('fa-eye-slash');
            } else {
              passwordField.setAttribute('type', 'password');
              togglePassword.classList.remove('fa-eye-slash');
              togglePassword.classList.add('fa-eye');
            }
          });

        </script>
    </div>
  </div>
</body>

</html>

templates/passreset.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Password Reset</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='passreset.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
</head>

<body>
  <div class="container">
    <div class="wrapper">
      <div class="title"><span>Password Reset</span></div>
      <form action="{{ url_for('views.passreset') }}" method="POST">
        <div class="row">
          <div class="icon"><i class="fas fa-envelope"></i></div>
          <input type="email" name="email" placeholder="Email" required>
        </div>
        <div class="row">
          <div class="icon"><i class="fas fa-key"></i></div>
          <input type="password" name="new_password" placeholder="New Password" required>
        </div>
        <div class="row">
          <div class="icon"><i class="fas fa-key"></i></div>
          <input type="password" name="confirm_password" placeholder="Confirm New Password" required>
        </div>
        <div class="row button">
          <input type="submit" value="Reset Password">
        </div>
      </form>
    </div>
  </div>
</body>

</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='profile.css') }}">
    <title>User Profile</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#logout').click(function () {
                $.ajax({
                    type: 'POST',
                    url: '{{ url_for("views.logout") }}',
                    success: function (response) {
                        window.location.href = '{{ url_for("views.login") }}';
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
</head>

<body>
    <div class="profile-container">
        <div class="card-header">
            <h1>User Profile</h1>
        </div>
        <div class="profile-details">

            <div class="profile-field">
                <label for="email">Email:</label>
                <p id="email">{{ user.email }}</p>
            </div>

            <div class="profile-field">
                <label for="fullName">Full Name:</label>
                <p id="fullName">{{ user.name }}</p>
            </div>

            <div class="profile-field">
                <label for="username">Username:</label>
                <p id="username">{{ user.username }}</p>
            </div>

            <div class="profile-field">
                <label for="age">Age:</label>
                <p id="age">{{ user.age }}</p>
            </div>

            <div class="profile-field">
                <label for="gender">Gender:</label>
                <p id="gender">{{ user.gender }}</p>
            </div>

            <div class="profile-field">
                <label for="profileDescription">Profile Description:</label>
                <p id="profileDescription">{{ user.profileDescription }}</p>
            </div>

            <div class="profile-field">
                <label for="linkedin">LinkedIn Profile URL:</label>
                <p id="linkedin">{{ user.linkedinProfURL }}</p>
            </div>

            <div class="profile-field">
                <label for="designation">Designation:</label>
                <p id="designation">{{ user.designation }}</p>
            </div>

            <div class="profile-field">
                <label for="country">Country:</label>
                <p id="country">{{ user.country }}</p>
            </div>

            <div class="profile-field">
                <label for="disabled">Disabled:</label>
                <p id="disabled">{{ user.disabled }}</p>
            </div>

            <div class="profile-field">
                <label for="experience">Fresher/Experienced:</label>
                <p id="experience">{{ user.FreshExp }}</p>
            </div>

            <div class="profile-field">
                <label for="joinedDate">Joined Date:</label>
                <p id="joinedDate">{{ user.joinedDate }}</p>
            </div>
        </div>

        <div class="profile-actions">
            <button id="logout">Log Out</button>
        </div>
    </div>
</body>

</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <title>Responsive Registration Form | CodingLab</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='reg.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="container">
        <div class="title">Registration</div>
        <div class="content">
            <form method="POST" action="{{ url_for('views.reg') }}">
                <div class="user-details">
                    <div class="input-group">
                        <div class="input-box">
                            <span class="details">Full Name</span>
                            <input type="text" placeholder="Enter your name" name="name" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Country</span>
                            <input type="text" placeholder="Enter your country" name="country" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Are you a Fresher or Experienced?</span>
                            <select name="FreshExp" required>
                                <option value="" disabled selected>Select an option</option>
                                <option value="Fresher">Fresher</option>
                                <option value="Experienced">Experienced</option>
                            </select>
                        </div>
                    
                    </div>
                    <div class="input-group">
                        <div class="input-box">
                            <span class="details">LinkedIn Profile URL</span>
                            <input type="text" placeholder="Enter your LinkedIn Profile URL" name="linkedinProfURL" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Designation</span>
                            <input type="text" placeholder="Enter your designation" name="designation" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Email</span>
                            <input type="text" placeholder="Enter your email" name="email" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <div class="input-box">
                            <span class="details">Password</span>
                            <input type="password" placeholder="Enter your password" name="password" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Age</span>
                            <input type="text" placeholder="Enter your age" name="age" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Do you have any Disability?</span>
                            <div class="radio-options">
                                <label>
                                    <input type="radio" name="disabled" value="Yes" required> Yes
                                </label>
                                <label>
                                    <input type="radio" name="disabled" value="No" required> No
                                </label>
                            </div>
                        </div>
                        
                    </div>
                    <div class="input-group">
                        <div class="input-box">
                            <span class="details">Profile Description</span>
                            <input type="text" placeholder="Enter your profile description" name="profileDescription" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Username</span>
                            <input type="text" placeholder="Enter your username" name="username" required>
                        </div>
                        <div class="input-box">
                            <span class="details">Gender</span>
                            <input type="text" placeholder="Male | Female" name="gender" required>
                        </div>
                    </div>
                </div>
                <div class="gender-details">
                </div>
                <div class="profile-actions">
                    <div class="button">
                        <input class="register-button" type="submit" value="Register">
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>

</html>